name: 'Update Linear issue'
description: 'Action updates a Linear issue'
inputs:
  branch:
    description: 'Name of the branch'
    required: true
  title:
    description: 'Title of the PR'
  description:
    description: 'Description of PR'         
  comment:
    description: 'Comment text to be added in Linear'
    required: true
  label:
    description: 'Label name to be added in Linear'     
  token:
    description: 'Access token for Linear API'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.branch }}
    - ${{ inputs.title }}
    - ${{ inputs.description }}
    - ${{ inputs.comment }}
    - ${{ inputs.label }}