name: "Linear GHA Client"
description: "Exposes Linear GraphQL API to GitHub Actions"
inputs:
  token:
    description: "Access token for Linear API"
    required: true
  ref_value:
    description: "Reference value to search for (e.g. branch name, PR title or PR description)"
    required: true
  object_type:
    description: "Object type (e.g. comment, state or label)"
    required: true
  object_value:
    description: "Object value"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.ref_value }}
    - ${{ inputs.object_type }}
    - ${{ inputs.object_value }}
