name: 'Update Linear issue'
description: 'Action updates a Linear issue'
inputs:
  token:
    description: 'Access token for Linear API'
    required: true
  object_type:
    description: 'Linear object type to be updated'
    required: true
  object_value:
    description: 'Linear object value'
    required: true
  label:
    description: 'Label to add' 
  branch:
    description: 'Name of the branch'
  title:
    description: 'Title of the PR'
  description:
    description: 'Description of PR'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.object_type }}
    - ${{ inputs.object_value }}
    - ${{ inputs.label }}
    - ${{ inputs.branch }}
    - ${{ inputs.title }}
    - ${{ inputs.description }}